### ISSUE TITLE
Is spoofing the mac address enough for impersonating other devices ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [ElginCiani/mac-address-changer#1]

**Comment by ElginCiani** [comment]
The answer is (as it usually is) "It depends." The main point of the MAC address is that every device has a unique one, so network traffic knows where to go. It's unencrypted, and some protocols may rely on this address to identify you for a variety of different reasons, so changing it helps mask you. It should also be enough to impersonate other devices, but I wouldn't personally rely only on this if the stakes are high.

**Comment by minanagehsalalma** [comment]
> but I wouldn't personally rely only on this 

@ElginCiani what would you rely on ?

**Comment by ElginCiani** [comment]
It'd depend on what you're trying to do exactly. MAC address spoofing is probably enough though generally.
